spring:
  liquibase:
    change-log: "classpath:db/changelog/user-changelog.xml"

  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
