spring:
  liquibase:
    change-log: "classpath:db/changelog/user-changelog.xml"

  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver


app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb

app-jwt-expiration-milliseconds: 604800000

logging:
  level:
    root: debug
